### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by flakelv** [flakelv/repo-exercise#1]
- [ ] Create page design
- [ ] Create basic page structure 
  - [ ] Header
  - [ ] Main section
  - [ ] Footer
  - [ ] Dropdown (Burger menu)
